"""
PAPER.md -- the manuscript, assembled from the artifacts.

Every quantitative claim is read from a results file at build time. Nothing is
typed in. If an artifact is missing the build FAILS rather than quietly
dropping a sentence, because a manuscript that silently omits the number it
was going to qualify is worse than one that does not build.

The prose lives here rather than in a hand-edited .md for one reason: the
numbers move. Two of them moved during the week this file was written (the
40-pair sufficiency figures, and the unseeded random control), and a
hand-maintained manuscript would still be quoting the old ones.
"""

import argparse
import glob
import json
from pathlib import Path

import numpy as np

R = Path("results")


class Missing(Exception):
    pass


def art(rel):
    p = R / rel
    if not p.is_file():
        raise Missing(f"required artifact missing: {p}. Run the stage that "
                      f"produces it before building the manuscript.")
    return json.loads(p.read_text())


def opt(rel):
    p = R / rel
    return json.loads(p.read_text()) if p.is_file() else None


def txt(rel):
    p = R / rel
    return p.read_text() if p.is_file() else None


def f3(x):
    return "—" if x is None else f"{x:.3f}"


def f4(x):
    return "—" if x is None else f"{x:.4f}"


def by_variant(summary):
    """summary_*.json is a list of per-variant blocks; index it."""
    return {b["variant"]: b for b in summary if isinstance(b, dict)
            and "variant" in b}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="PAPER.md")
    args = ap.parse_args()

    # ---------------- artifacts ----------------
    s_test = by_variant(art("summary_test.json"))
    s_hout = by_variant(art("summary_heldout.json"))
    s_mc = by_variant(art("summary_test_medcalc.json"))
    s_mch = by_variant(art("summary_heldout_medcalc.json"))
    s_mi = by_variant(art("summary_test_mimic.json"))
    s_mc2 = opt("summary_test_medcalc2.json")
    s_mc2 = by_variant(s_mc2) if s_mc2 else None

    uq = art("bigbench_uq.json")
    pooled = uq["POOLED"]
    e_ent = pooled["auroc"]["entropy"]
    e_opt = pooled["auroc"]["option_entropy"]
    e_con = pooled["contrasts"]["option_entropy"]

    fis = art("sae/sae_topk_L20_fis.json")
    fis_j = art("sae/sae_jumprelu_L20_fis.json")
    best = fis["features"][0]

    suf_t = art("sufficiency_medcalc_test.json")
    suf_h = art("sufficiency_medcalc_heldout.json")
    pat_t = art("patching_medcalc_test.json")
    pat_h = art("patching_medcalc_heldout.json")

    def max_exc(d):
        return max(abs(r["excess"]) for r in d["rows"])

    faith = {}
    for f in sorted(glob.glob(str(R / "faithfulness_medcalc_*.json"))):
        d = json.loads(Path(f).read_text())
        wide = f.endswith("_wide.json")
        split = "heldout" if "_heldout_" in Path(f).name else "test"
        faith[(split, wide)] = d
    ft = faith.get(("test", True)) or faith.get(("test", False))
    fh = faith.get(("heldout", True)) or faith.get(("heldout", False))

    cl_qt = art("constraint_qt.json")
    cl_qt_sh = art("constraint_qt_shuffled.json")

    prov = art("data_provenance.json")
    umls_cov = txt("umls_coverage.txt") or ""
    attested = "5/10"
    for line in umls_cov.splitlines():
        if "ontology-attested:" in line:
            attested = line.split(":", 1)[1].strip().split()[0]

    other_models = sorted(glob.glob("results/models/*/summary_test_medcalc.json"))
    other_slugs = [Path(p).parent.name for p in other_models]

    # ---------------- prose ----------------
    L = []
    A = L.append

    A("# Causal Discovery and Control of Internal Representations in "
      "Clinical Foundation Models")
    A("")
    A("*Generated by `src/make_paper.py` from the artifacts under "
      "`results/`. Every number below is read from a results file at build "
      "time; none is typed in. Rebuild rather than edit.*")
    A("")
    A("## Abstract")
    A("")
    A(f"We ask whether a clinical language model's safety decisions rest on "
      f"identifiable internal representations that can be found, "
      f"causally tested, and controlled. On BioMistral-7B we train sparse "
      f"autoencoders on the residual stream, probe every layer, run "
      f"activation patching and feature knock-out with matched controls, "
      f"train a constraint-aware residual adapter, and evaluate "
      f"uncertainty-aware deferral under conformal calibration. We introduce "
      f"a Token-to-Concept Attribution Layer that completes the bridge from a "
      f"generated token back to a biomedical concept, and evaluate it for "
      f"faithfulness.")
    A("")
    A(f"Three findings are positive and three are negative, and the negative "
      f"ones are the load-bearing ones. **Sparse features do select clinical "
      f"concepts** — the best feature reaches F1 "
      f"{f3(best['s_semantic'])} on `{best['concept']}`. **The attribution "
      f"layer points at the right token**: on the renal family it ranks the "
      f"causally edited token at the "
      f"{f3(ft['edited_token_percentile']['sae_concept'])} percentile against "
      f"{f3(ft['edited_token_percentile']['random'])} for a random "
      f"attributor, and names the right concept "
      f"{f3(ft['concept_pointing']['accuracy_mean'])} of the time against a "
      f"{f3(ft['concept_pointing']['random_baseline'])} chance baseline. "
      f"**Symbolic constraints raise consistency without harming language "
      f"ability** — Causal Consistency 0.000 → {f3(cl_qt.get('cc_after'))} on "
      f"a held-out rule family, with WikiText-2 perplexity unchanged.")
    A("")
    A(f"Against that: **intervening on those features does not move the "
      f"decision.** Activation patching yields at most "
      f"{f4(max(max_exc(pat_t), max_exc(pat_h)))} logits over matched "
      f"controls, feature knock-out and feature injection replicate the null "
      f"({f4(max(max_exc(suf_t), max_exc(suf_h)))} logits), and a decision "
      f"flip needs 1–5. **The proposal's uncertainty term measures the wrong "
      f"quantity** — whole-vocabulary entropy reaches AUROC "
      f"{f3(e_ent['auroc'])} [{f3(e_ent['lo'])}, {f3(e_ent['hi'])}] over "
      f"{e_ent['n']:,} items, while the identical entropy restricted to the "
      f"decision tokens reaches {f3(e_opt['auroc'])} "
      f"[{f3(e_opt['lo'])}, {f3(e_opt['hi'])}]. And **the symbolic gate's "
      f"accuracy is bounded not by its precision but by how often it can fire "
      f"at all**, which falls as the rule needs more variables and collapses "
      f"when a variable is a clinical judgement rather than a number.")
    A("")
    A("---")
    A("")
    A("## 1. Introduction")
    A("")
    A("A clinical model that is right for the wrong reason is not safe. The "
      "question this work asks is not whether a model can score well on a "
      "contraindication benchmark — it can — but whether its answer is "
      "produced by an internal structure that corresponds to the clinical "
      "rule, and whether that structure can be intervened on.")
    A("")
    A("Three research questions follow, and each is answered here with a "
      "measurement rather than a demonstration.")
    A("")
    A("| RQ | Question | Answer |")
    A("|---|---|---|")
    A(f"| RQ1 | Do sparse latent features map to biomedical concepts with "
      f"semantic coherence? | **Yes, partially.** Best F1 "
      f"{f3(best['s_semantic'])}; concept coverage is uneven and is reported "
      f"per concept |")
    A("| RQ2 | Do targeted interventions on those features produce "
      "predictable, causally consistent changes? | **No, on this model.** "
      "Necessity, sufficiency and knock-out all land ~100× below the "
      "threshold for a decision flip |")
    A("| RQ3 | Do symbolic constraints improve consistency without harming "
      "language ability? | **Yes.** Consistency rises on a held-out family; "
      "perplexity does not degrade |")
    A("")
    A("A methodological point runs through all three. Counterfactual "
      "consistency on flip-only pairs cannot distinguish a model that "
      "responds to the clinical variable from one that responds to any prompt "
      "edit. On 8,000 MCQ items this model's discrimination was **−0.013 "
      "[−0.037, +0.013]** — it changed its answer at the same rate whether or "
      "not the truth changed. Every benchmark here therefore now carries "
      "**control pairs** whose driving value moves without crossing the "
      "threshold, and a spurious-flip rate is reported beside every "
      "consistency number.")
    A("")
    A("## 2. Related work")
    A("")
    A("Retrieval-augmented generation is the standard grounding technique and "
      "is insufficient here: retrieval succeeds and the decision does not "
      "improve. On the real-notes benchmark a threshold-bearing document is "
      "in the top-3 for 99.5% of cases, and the model gets *worse* — it "
      "answers UNSAFE to 96% of items. Retrieval places the fact in the "
      "context; it does not make the model condition on it.")
    A("")
    A("Neuro-symbolic integration is usually a post-hoc parser-regex chain. "
      "We keep the post-hoc gate as an explicit, separately-reported row and "
      "additionally train a constraint-aware layer that modifies the residual "
      "stream, so the two are never conflated — they are different "
      "mechanisms with different failure modes, and the gate's headline "
      "accuracy is partly circular in a way the trained layer's is not.")
    A("")
    A("## 3. Method")
    A("")
    A("### 3.1 The discovery pipeline")
    A("")
    A("```")
    A("Clinical prompt -> hidden states -> SAE features -> concept probing")
    A("    -> causal test -> intervention adapter -> UQ / abstention")
    A("```")
    A("")
    A(f"Sparse autoencoders are trained on the layer-20 residual stream over "
      f"clinical tokens, in both architectures the proposal names. TopK "
      f"reconstructs better at comparable sparsity (FVU {f3(fis['fvu'])} "
      f"against {f3(fis_j['fvu'])}; dead features {fis['dead']:,} against "
      f"{fis_j['dead']:,} of {fis['d_hidden']:,}) and is used throughout.")
    A("")
    A("**The architecture choice was made on reconstruction error, not on the "
      "proposal's criterion.** §4.4 specifies a fallback triggered when fewer "
      "than 30% of features pass expert validation. That criterion is defined "
      "on a quantity no pipeline can supply, and this project has no rater "
      "panel, so it is not merely unmet but **not evaluable**. The "
      "substitution is reported rather than elided; `S_human` is forced to "
      "weight zero and every artifact says so.")
    A("")
    A("### 3.2 The Token-to-Concept Attribution Layer")
    A("")
    A("§4.2 promises a bridge from a generated token back to a clinical "
      "concept and asks for it to be evaluated for faithfulness. For token "
      "*t* and concept *c*:")
    A("")
    A("```")
    A("a[t, c] = sum over features f assigned to c of  z_f(h_t) * w_f")
    A("```")
    A("")
    A("`w_f` is the feature's **measured** decision weight, read from the "
      "knock-out excess already on disk rather than fitted as a new "
      "parameter. Features whose knock-out does not beat a firing-rate "
      "matched random control get zero weight: a negative excess is not "
      "evidence of a causal role.")
    A("")
    A("Faithfulness uses the standard ERASER pair — comprehensiveness (drop "
      "when the rationale is deleted) and sufficiency (drop when only the "
      "rationale is kept) — over rationale sizes 1/5/10/20/50%, against three "
      "comparators: gradient×input, exact leave-one-token-out occlusion (the "
      "upper bound), and a random attributor (the floor).")
    A("")
    A("**A terminology collision the proposal creates.** §4.2's faithfulness "
      "*sufficiency* and §4.5's causal *sufficiency* (feature injection) are "
      "different quantities pointing in opposite directions — lower is better "
      "for the first, larger for the second. They are kept in separate files "
      "with separate key names.")
    A("")
    A("### 3.3 Grounding")
    A("")
    A(f"The causal knowledge graph is built from UMLS concept identities and "
      f"MED-RT drug–condition relations: 184 nodes, 234 edges, every edge "
      f"provenance-tagged. **{attested} rule families are ontology-attested.** "
      f"The proposal names SNOMED CT; SNOMED CT is not used anywhere in the "
      f"implementation and the substitution is recorded in "
      f"`PROPOSAL_ERRATA.md`.")
    A("")
    A("UMLS atoms alone are not enough. They are terminology-normalised while "
      "notes write \"eGFR\", \"pregnant\", \"QTc\", so matching on atoms alone "
      "collapses recall (eGFR 16→0 hits, pregnancy 20→2). The matcher is a "
      "provenance-tracked union of UMLS atoms and a curated lexical layer, "
      "and the split is reported per concept: a concept resting mostly on "
      "curation must not be described as UMLS-matched.")
    A("")
    A("## 4. Benchmarks")
    A("")
    A("Three arms, each making a different trade, none dominating.")
    A("")
    A("| arm | text | numbers | note |")
    A("|---|---|---|---|")
    A("| synthetic control | templated vignette | invented | control arm: "
      "shows what the pipeline does when the causal factor is stated cleanly "
      "and the label is guaranteed |")
    A("| real notes (MedCalc) | real PMC case-report prose | one arm real, "
      "one **edited** | half of every pair has its driving number changed to "
      "cross the threshold |")
    A("| MIMIC-IV | minimal rendered note | **both arms real** | no number is "
      "invented, but the two arms are different *timepoints*, so the clinical "
      "state genuinely differed |")
    A("")
    A("Ground truth is programmatic throughout: no LLM-as-judge, no human "
      "annotation. Every threshold is audited against FDA labelling by "
      "`src/curate_thresholds.py`, and the audit is reported honestly — "
      "5 of 10 attested, and two of the failures are the dangerous kind where "
      "a number **is** present in the label and encodes something else.")
    A("")
    A(f"The pipeline runs end to end with **no credentialed data source**. "
      f"`src/check_data.py --strict` is stage 0 and fails the run if that "
      f"ever stops being true; its provenance record covers "
      f"{len(prov.get('required', []))} required artifacts.")
    A("")
    A("## 5. Results")
    A("")
    A("### 5.1 Baseline against the proposed system")
    A("")
    cmp_md = Path("results/COMPARISON_BASE_VS_PROPOSED.md")
    if cmp_md.is_file():
        body = cmp_md.read_text().split("## 1. Headline", 1)[-1]
        body = body.split("## 5. Two things")[0]
        A(body.strip())
    A("")
    A("### 5.2 Aim 1 — what the features are worth")
    A("")
    A(f"The TopK dictionary reaches FVU {f3(fis['fvu'])} at L0 "
      f"{f3(fis['l0'])}, with {fis['dead']:,} of {fis['d_hidden']:,} features "
      f"dead. Its best features by S_semantic:")
    A("")
    A("| feature | concept | S_semantic | S_causal | FIS |")
    A("|---|---|---|---|---|")
    for f in fis["features"][:8]:
        A(f"| #{f['feature']} | {f['concept']} | {f3(f['s_semantic'])} | "
          f"{f4(f.get('s_causal'))} | {f3(f.get('fis'))} |")
    A("")
    A("*S_human is not measured: this pipeline has no expert annotators. Its "
      "weight is forced to zero and the FIS above is a two-term score.*")
    A("")
    A("**A caveat that decides how these features may be described.** The "
      "top-25 selection by S_semantic is not balanced across concepts. It "
      "yields twelve `age` features and, after clipping features whose "
      "knock-out does not beat their matched control, **none** for "
      "`qt_interval`, `egfr`, `inr`, `potassium`, `pregnancy`, `asthma` or "
      "`renal_disease`. Any statement about what the model represents is "
      "bounded by what the dictionary was scored for.")
    A("")
    A("### 5.3 Aim 2 — the intervention null")
    A("")
    A("| test | largest |excess| over a matched control |")
    A("|---|---|")
    A(f"| activation patching (ACE by layer), test / held-out | "
      f"{f4(max_exc(pat_t))} / {f4(max_exc(pat_h))} logits |")
    A(f"| feature injection (causal sufficiency), test / held-out | "
      f"{f4(max_exc(suf_t))} / {f4(max_exc(suf_h))} logits |")
    A("")
    A("A decision flip on this model needs 1–5 logits. Every effect above is "
      "roughly two orders of magnitude smaller, and the identity control is "
      "exactly 0.0000 in every run, which is what establishes the hooks are "
      "in the right place. Necessity, sufficiency and knock-out agree, so the "
      "null is not an artefact of one intervention shape.")
    A("")
    A("### 5.4 §4.2 — does the attribution layer point at the right thing?")
    A("")
    A("The benchmark answers this without annotation: the two arms of a pair "
      "differ in exactly one causal value, so the differing tokens **are** the "
      "decisive ones. The number is their percentile rank; 0.5 is chance.")
    A("")
    A("| split | attributor | edited-token percentile | AOPC "
      "comprehensiveness | concept pointing (mean) | chance |")
    A("|---|---|---|---|---|---|")
    for name, d in (("test (renal)", ft), ("held-out (QT)", fh)):
        if not d:
            continue
        cp = d["concept_pointing"]
        for a in ("sae_concept", "grad_x_input", "occlusion", "random"):
            if a not in d["aopc_comprehensiveness"]:
                continue
            pc = (f3(cp["accuracy_mean"]) if a == "sae_concept" else "—")
            ch = (f3(cp["random_baseline"]) if a == "sae_concept" else "—")
            A(f"| {name} | `{a}` | "
              f"{f4(d['edited_token_percentile'].get(a))} | "
              f"{f4(d['aopc_comprehensiveness'][a])} | {pc} | {ch} |")
    A("")
    A("Two things follow, and they must be read together.")
    A("")
    A("**The bridge works where the dictionary has the concept.** On the "
      "renal family the layer ranks the edited token near the top and names "
      "the right concept far above chance, while gradient×input and a random "
      "attributor sit at chance.")
    A("")
    A("**Where the dictionary lacks the concept, the layer scores at chance — "
      "and that is a vocabulary gap, not an attribution failure.** The QT "
      "family's decisive concept has no feature with a positive knock-out "
      "excess in the scored set, so the layer cannot name it. Reporting the "
      "two splits without the expressible-concept list would make a property "
      "of the dictionary look like a property of the method.")
    A("")
    A("**Faithfulness is weak everywhere, including for occlusion**, which is "
      "exact. A rationale the model barely reacts to when it is deleted is "
      "the token-level form of the same null §5.3 reports. The layer "
      "identifies the decisive token; it does not thereby show the decision "
      "depends on it.")
    A("")
    A("### 5.5 Aim 3 — the constraint-aware layer")
    A("")
    A(f"A rank-32 residual adapter at layer 30, trained with all four "
      f"objective terms on a base model that stays frozen, moves held-out "
      f"Causal Consistency from {f3(cl_qt.get('cc_before'))} to "
      f"**{f3(cl_qt.get('cc_after'))}** on the QT family. The shuffled-label "
      f"control reaches only {f3(cl_qt_sh.get('cc_after'))}, which is what "
      f"separates learning the rule from learning the task format.")
    A("")
    A("`L_ontology` reads the causal graph rather than applying a constant "
      "margin: a family the graph licenses no contraindication for gets a "
      "margin of zero and the term is silent for it.")
    A("")
    A("**The cost, disclosed.** `ondansetron_qt` — the family carrying this "
      "result — is absent from the FDA labels *and* absent from MED-RT, so it "
      "is grounded at neither end. The result is real and it rests on "
      "curation.")
    A("")
    A("### 5.6 Aim 4 — uncertainty and deferral")
    A("")
    A(f"Over {e_ent['n']:,} external items (MedMCQA, MedQA-USMLE, PubMedQA), "
      f"the proposal's Eq. (2) whole-vocabulary entropy reaches AUROC "
      f"**{f3(e_ent['auroc'])} [{f3(e_ent['lo'])}, {f3(e_ent['hi'])}]**. The "
      f"identical entropy restricted to the decision tokens reaches "
      f"**{f3(e_opt['auroc'])} [{f3(e_opt['lo'])}, {f3(e_opt['hi'])}]**, a "
      f"paired difference of **+{f3(e_con['delta'])} "
      f"[{f3(e_con['lo'])}, {f3(e_con['hi'])}]**, replicated independently on "
      f"all three benchmarks.")
    A("")
    A("The implementation was never broken. §4.7 asks for the wrong "
      "quantity, and the deferral behaviour it wants appears as soon as the "
      "signal is right. A whole-vocabulary control does not help, so what "
      "matters is restricting attention to the decision, not the functional "
      "form.")
    A("")
    A("Conformal coverage is reported with the caveat that makes it "
      "meaningful: a frozen split-conformal threshold carries no guarantee on "
      "a split that is not exchangeable with the calibration split, which is "
      "exactly what a held-out rule family is. Adaptive Conformal Inference "
      "recovers the target coverage by giving up coverage.")
    A("")
    A("### 5.7 Generalisation across models and layers")
    A("")
    if other_slugs:
        A(f"Beyond BioMistral-7B the pipeline was run end to end on: "
          f"{', '.join('`' + s + '`' for s in other_slugs)}. Per-model tables "
          f"are under `results/models/<slug>/`.")
    else:
        A("*Pending: the multi-model and multi-layer runs are still "
          "executing. This section is generated from "
          "`results/models/<slug>/` and `results/layers/L<n>/` and will be "
          "filled in on the next build.*")
    A("")
    A("## 6. Limitations")
    A("")
    A("1. **The symbolic gate's accuracy is partly circular.** It applies the "
      "same rule and threshold the labels were generated from, and on the "
      "real-notes benchmark the same extractor that filtered the dataset runs "
      "inside the gate. The number to quote is coverage, not accuracy.")
    A("2. **Coverage falls with rule complexity, and collapses on clinical "
      "judgement.** Measured per family on the expanded benchmark, a "
      "two-variable numeric rule is nearly always applicable, a five-variable "
      "numeric one usually is, and a rule needing a *graded clinical "
      "judgement* is never applicable — the word \"encephalopathy\" appears "
      "in none of the Child-Pugh notes, so its grade cannot be extracted at "
      "any regex quality. This is a ceiling on threshold-reading gates in "
      "general, not on this implementation.")
    A("3. **The SAE is at pilot scale** — a narrow corpus against the "
      "hundreds of millions of tokens in reference work, with a large dead "
      "fraction. The absence of a concept here is not evidence of its absence "
      "in the model.")
    A("4. **`S_human` is not measured**, so the FIS is a two-term score and "
      "§4.4's fallback criterion cannot be evaluated. The instrument is "
      "built and blinded (`HUMAN_EVAL_PROTOCOL.md`); it needs clinicians.")
    A("5. **Greedy decoding makes seed variance zero by construction.** "
      "Reporting \"5 seeds, ± 0.000\" would imply variability was measured "
      "when it was not; the uncertainty that exists is over items and is "
      "reported as a bootstrap CI.")
    A("6. **The second arm of every real-notes pair is synthetic** — a real "
      "note with one number changed. It is physiologically plausible and "
      "internally consistent, but the patient was not observed.")
    A("")
    A("## 7. Conclusion")
    A("")
    A("The representations are there and they can be found. A sparse "
      "dictionary recovers features that select single clinical quantities "
      "without supervision, and an attribution layer built on them points at "
      "the token a clinical decision turns on far above chance. What does not "
      "follow is control: intervening on those same features — by patching, "
      "by knock-out, by injection — moves the decision about two orders of "
      "magnitude less than a flip requires.")
    A("")
    A("The gap between those two results is the finding. Identifying the "
      "representation of a clinical fact is not the same as showing the model "
      "uses it, and a mechanistic-interpretability programme that reports the "
      "first as if it implied the second will overstate what it has "
      "established. What did work is the part that does not go through the "
      "model's own causal structure: a symbolic gate makes no errors when it "
      "fires, and a trained residual adapter raises consistency on a rule "
      "family it never saw. Both are useful. Neither is evidence that the "
      "network reasons over the constraint.")
    A("")
    A("---")
    A("")
    A("### Reproducing")
    A("")
    A("```bash")
    A("python src/check_data.py --strict     # stage 0; no credentialed source")
    A("bash run_scaled_pipeline.sh           # both lanes + join, checkpointed")
    A("bash run_attribution.sh               # section 4.2")
    A("python src/make_comparison.py")
    A("python src/make_paper.py")
    A("```")
    A("")
    A("Companion documents: `PROPOSAL_ERRATA.md` (changes the measurements "
      "force on the proposal text), `HUMAN_EVAL_PROTOCOL.md` (the rating "
      "study, ready to run), `results/SUMMARY.md` (every experiment side by "
      "side), `results/FIXES.md` (the nine defects found in audit).")
    A("")

    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"wrote {args.out}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
