"""
results/attribution.md -- the section 4.2 Token-to-Concept Attribution Layer.

Numbers come from results/faithfulness_*.json, never from a log and never
typed in, the same rule make_summary.py follows.
"""

import argparse
import glob
import json
from pathlib import Path

K_LABEL = {0.01: "1%", 0.05: "5%", 0.10: "10%", 0.20: "20%", 0.50: "50%"}


def fmt(x, nd=4):
    return "—" if x is None else f"{x:.{nd}f}"


def load(pattern):
    out = {}
    for f in sorted(glob.glob(pattern)):
        d = json.loads(Path(f).read_text())
        out[f] = d
    return out


def split_name(path):
    n = Path(path).stem
    if "_heldout_" in n:
        return "held-out (QT / ondansetron)"
    return "test (renal / metformin)"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results")
    ap.add_argument("--out", default="results/attribution.md")
    args = ap.parse_args()
    R = Path(args.results)

    narrow = load(str(R / "faithfulness_medcalc_*_biomistral-7b.json"))
    wide = load(str(R / "faithfulness_medcalc_*_biomistral-7b_wide.json"))
    if not narrow and not wide:
        raise SystemExit("no faithfulness_*.json found; run attribution.py")

    any_d = next(iter((wide or narrow).values()))
    L = [
        "# Section 4.2: the Token-to-Concept Attribution Layer",
        "",
        "*Generated by `src/make_attribution_report.py` from "
        "`results/faithfulness_*.json`. Do not edit the numbers by hand.*",
        "",
        "Section 4.2 of the proposal promises a bridge from a generated token "
        "back to a clinical concept, and says it \"will be quantitatively "
        "evaluated for faithfulness using standard sufficiency and "
        "comprehensiveness metrics\". Until 2026-09-06 the repository "
        "implemented that bridge as far as the probing classifier and stopped; "
        "`src/attribution.py` completes it and measures it.",
        "",
        "**A naming collision that has to be stated once, loudly.** "
        "`sufficiency` already means Aim 2 causal *feature injection* in this "
        "project (`patching.py --mode sufficiency`, "
        "`results/sufficiency_medcalc_*.json`). ERASER sufficiency below is a "
        "different quantity measured on a different object, and lower is "
        "better for it. The two must never be quoted into the same sentence.",
        "",
        "## 1. What the layer computes",
        "",
        "For token *t* and concept *c*, at the layer the SAE dictionary was "
        "fitted on:",
        "",
        "```",
        "a[t, c] = sum over features f assigned to concept c of  z_f(h_t) * w_f",
        "```",
        "",
        "`z_f(h_t)` is the sparse code of the residual stream at position *t*. "
        "`w_f` is the feature's **measured** decision weight, read from the "
        "knock-out excess already on disk rather than introduced as a new free "
        "parameter; features whose knock-out does not beat their firing-rate "
        "matched random control are given zero weight, because a negative "
        "excess is not evidence of a causal role.",
        "",
        f"Layer {any_d['layer']}, model `{any_d['model_id']}`, concept "
        f"vocabulary `{any_d['concept_source']}`.",
        "",
        "## 2. Does it point at the right token?",
        "",
        "The benchmark answers this without any annotation. The two arms of a "
        "pair differ in exactly one causal value, so **the tokens that differ "
        "ARE the decisive tokens**. The number below is the percentile rank "
        "the attributor gives them among the note's tokens; 0.5 is chance.",
        "",
    ]

    def table(ds, title):
        rows = [f"### {title}", "",
                "| split | attributor | edited-token percentile | "
                "AOPC comprehensiveness (higher better) | "
                "AOPC ERASER sufficiency (lower better) |",
                "|---|---|---|---|---|"]
        for f, d in sorted(ds.items()):
            for n in d["aopc_comprehensiveness"]:
                rows.append(
                    f"| {split_name(f)} | `{n}` | "
                    f"{fmt(d['edited_token_percentile'].get(n))} | "
                    f"{fmt(d['aopc_comprehensiveness'][n])} | "
                    f"{fmt(d['aopc_sufficiency'][n])} |")
        rows.append("")
        for f, d in sorted(ds.items()):
            rows.append(f"{split_name(f)}: n={d['n_items']} items, "
                        f"{d['n_edited_pairs']} pairs usable for the "
                        f"edited-token check, occlusion run on "
                        f"{d['n_occlusion_items']} items.")
        rows.append("")
        return rows

    if narrow:
        L += table(narrow, "Top-25 feature vocabulary (the 2026-09-02 scoring)")
    if wide:
        L += table(wide, "Top-100 feature vocabulary")

    L += [
        "`occlusion` deletes one token at a time and measures the drop, so it "
        "is the exact answer the cheap attributors are approximating and the "
        "upper bound on what any of them can reach. `random` is the floor.",
        "",
        "## 3. Does it point at the right concept?",
        "",
        "Concept-pointing accuracy is the fraction of items whose "
        "top-attributed concept is one the family's decision actually turns "
        "on. Its baseline is picking uniformly among the concepts the note "
        "mentions at all, so a layer that simply fires on whatever is present "
        "scores at chance.",
        "",
        "Two aggregations are reported because they answer different "
        "questions. **sum** adds a concept's features together, so a concept "
        "the dictionary happens to have twelve features for outranks one it "
        "has two for regardless of the note. **mean** divides by that count. "
        "The gap between them measures how much of the readout is the "
        "dictionary's composition rather than the note's content.",
        "",
        "| vocabulary | split | accuracy (sum) | accuracy (mean) | "
        "random baseline | n |",
        "|---|---|---|---|---|---|",
    ]
    for label, ds in (("top-25", narrow), ("top-100", wide)):
        for f, d in sorted(ds.items()):
            c = d["concept_pointing"]
            L.append(f"| {label} | {split_name(f)} | "
                     f"{fmt(c['accuracy_sum'], 3)} | "
                     f"{fmt(c['accuracy_mean'], 3)} | "
                     f"{fmt(c['random_baseline'], 3)} | {c['n']} |")
    L += [""]

    src = wide or narrow
    for f, d in sorted(src.items()):
        c = d["concept_pointing"]
        L += [f"Features per concept in the {('top-100' if wide else 'top-25')}"
              f" vocabulary ({split_name(f)}): "
              f"`{c['features_per_concept']}`.",
              "",
              f"Concepts the layer cannot express at all — no feature with a "
              f"positive knock-out excess: "
              f"**{sorted(set(c['features_per_concept']) - set(c['expressible_concepts']))}**.",
              ""]
        break

    L += [
        "## 4. What this shows, and what it does not",
        "",
        "Read the token result and the concept result together with the "
        "expressible-concept list. Where the dictionary has features for the "
        "concept a family's decision turns on, the bridge works; where it has "
        "none, the layer scores at chance for a reason that is a property of "
        "the dictionary, not of the attribution method. That distinction is "
        "measurable here and must be carried into any claim made about "
        "section 4.2.",
        "",
        "The faithfulness numbers are small across the board, **including for "
        "`occlusion`**, which is exact. A rationale that the model itself "
        "barely reacts to when it is deleted is the token-level form of the "
        "same null Aim 2 reports for activation patching and feature "
        "knock-out. The attribution layer identifies the decisive token; it "
        "does not thereby show the model's decision depends on it.",
        "",
        "## 5. Reproduce",
        "",
        "```bash",
        "python src/attribution.py \\",
        "    --data data/medcalc/counterfactual_test.jsonl \\",
        "    --sae results/sae/sae_topk_L20.npz \\",
        "    --fis results/sae/sae_topk_L20_fis.json \\",
        "    --limit 0 --occlusion_items 30",
        "python src/make_attribution_report.py",
        "```",
        "",
    ]
    Path(args.out).write_text("\n".join(L) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
